# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationevent',
            name='genpoliticidemag',
            field=models.DecimalField(decimal_places=15, help_text='Magnitude score for                                           number of deaths from genocide                                           and politicide (GEN/POLITICIDE)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='l52dyadasylumcorrpc',
            field=models.DecimalField(decimal_places=15, help_text='Meaning                                              unknown', max_digits=20),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='l52dyadasylumtotalpc',
            field=models.DecimalField(decimal_places=15, help_text='Meaning                                               unknown', max_digits=20),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='pts',
            field=models.DecimalField(decimal_places=15, help_text='average of two Political Terror                              Scales measuring human rights violations,                              ranging from 1 (best) to 5 (worst)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='sfallmax',
            field=models.DecimalField(decimal_places=15, help_text='Magnitude score for civil                                   war, ethnic war, or collapse of state                                   authority (DOMWAR/STATEFAIL)', max_digits=20),
        ),
    ]
