# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0002_auto_20170315_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationevent',
            name='destination_rwpvote',
            field=models.DecimalField(decimal_places=15, help_text='Meaning                                              unknown', max_digits=20),
        ),
    ]
