# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0003_auto_20170315_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['year'], 'verbose_name': 'Year', 'verbose_name_plural': 'Years'},
        ),
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(blank=True, help_text='If Known', null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='month',
            field=models.IntegerField(blank=True, help_text='If Known', null=True),
        ),
    ]
