# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0004_auto_20170321_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['year', 'month', 'day'], 'verbose_name': 'Date', 'verbose_name_plural': 'Dates'},
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='approvalrate',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='destination_gdp',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Destination                                          GDP Per Capita'),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='destination_rwpvote',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Meaning                                              unknown', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='destination_unemployment',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Destination                                                   Unemployment'),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='euplusasyl',
            field=models.IntegerField(blank=True, help_text='Meaning unknown', null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='free',
            field=models.IntegerField(blank=True, help_text='Sum of the two Freedom House                               indices of political rights and civil                               liberties, each ranging from 1 (most free)                               to 7 (least free) (AUTOCRACY)', null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='genpoliticidemag',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Magnitude score for                                           number of deaths from genocide                                           and politicide (GEN/POLITICIDE)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='l52dyadasylumcorrpc',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Meaning                                              unknown', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='l52dyadasylumtotalpc',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Meaning                                               unknown', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='origin_gdp',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Origin GDP Per Capita'),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='pts',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='average of two Political Terror                              Scales measuring human rights violations,                              ranging from 1 (best) to 5 (worst)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='recognisedrate',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='sfallmax',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Magnitude score for civil                                   war, ethnic war, or collapse of state                                   authority (DOMWAR/STATEFAIL)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='uppsalaexternalintensity',
            field=models.IntegerField(blank=True, help_text='Intensity of                                                   external conflicts, on an                                                   ordered categorical scale                                                   (0 = no conflict, 1 =                                                   25-999 deaths that year in                                                   minor conflict, 2 = 25-999                                                   deaths that year in                                                   conflict totaling 1000+                                                   deaths across years,                                                   3 = 1000+ deaths that                                                   year)', null=True),
        ),
    ]
