# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0005_auto_20170321_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationevent',
            name='free',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Sum of the two Freedom House                               indices of political rights and civil                               liberties, each ranging from 1 (most free)                               to 7 (least free) (AUTOCRACY)', max_digits=20, null=True),
        ),
    ]
