# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0006_auto_20170321_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='migrationevent',
            options={'ordering': ['origin__name', 'destination__name', 'date__year'], 'verbose_name': 'Migration Event', 'verbose_name_plural': 'Migration Events'},
        ),
    ]
