# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0008_worldborders'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='border',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visualisation.WorldBorders'),
        ),
    ]
