# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Political View')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Driving Event',
                'verbose_name_plural': 'Driving Events',
            },
        ),
        migrations.CreateModel(
            name='DurationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Duration Type')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Duration Type',
                'verbose_name_plural': 'Duration Types',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Location Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='MigrationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('date_y', models.IntegerField(verbose_name='Year')),
                ('date_m_from', models.IntegerField(verbose_name='From (Month)')),
                ('date_m_to', models.IntegerField(verbose_name='To (Month)')),
                ('date_uncertain', models.BooleanField(default=False, verbose_name='Uncertain Date?')),
                ('date_str', models.TextField(verbose_name='Date Notes')),
                ('who_str', models.TextField(blank=True, verbose_name='Who (Text)')),
                ('count_children', models.IntegerField(verbose_name='Child Count')),
                ('count_adults', models.IntegerField(verbose_name='Adult Count')),
                ('count_uncertain', models.BooleanField(default=False, verbose_name='Uncertain Counts?')),
                ('transport_desc', models.TextField(blank=True, verbose_name='Description of Transport')),
                ('length_of_stay_description', models.TextField(blank=True, verbose_name='Description of                                                  length of stay')),
                ('source', models.TextField(blank=True, verbose_name='Source')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Migration Event',
                'verbose_name_plural': 'Migration Events',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Organisation')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='PoliticalView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Political View')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Political View',
                'verbose_name_plural': 'Political Views',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Transport Type')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Transport Type',
                'verbose_name_plural': 'Transport Types',
            },
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='caregivers',
            field=models.ManyToManyField(blank=True, related_name='caregivers', to='drivingevents.Organisation', verbose_name='Caregivers'),
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='carered_for_by',
            field=models.ManyToManyField(blank=True, related_name='cared_for_by', to='drivingevents.Organisation', verbose_name='Cared For By'),
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='driving_events',
            field=models.ManyToManyField(blank=True, to='drivingevents.DrivingEvent'),
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='length_of_stay_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivingevents.DurationType', verbose_name='Length of Stay'),
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='location_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='drivingevents.Location', verbose_name='From (Location)'),
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='location_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='drivingevents.Location', verbose_name='To (Location)'),
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='political_view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivingevents.PoliticalView', verbose_name='Political View'),
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='transport_organisers',
            field=models.ManyToManyField(blank=True, related_name='transport_organisers', to='drivingevents.Organisation', verbose_name='Transport Organisers'),
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='transport_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drivingevents.TransportType', verbose_name='Transport Type'),
        ),
    ]
