# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingevent',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Event Name'),
        ),
    ]
