# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivingevents', '0002_auto_20170605_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationevent',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='drivingevents.Location', verbose_name='From (Location)'),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='drivingevents.Location', verbose_name='To (Location)'),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name'),
        ),
    ]
