# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingevents', '0003_auto_20170605_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationevent',
            name='transport_type',
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='transport_types',
            field=models.ManyToManyField(blank=True, related_name='transport_types', to='drivingevents.TransportType', verbose_name='Transport Types'),
        ),
    ]
