# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingevents', '0004_auto_20170605_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationevent',
            name='length_of_stay_description',
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='length_of_stay_desc',
            field=models.TextField(blank=True, verbose_name='Description of                                           length of stay'),
        ),
        migrations.RemoveField(
            model_name='migrationevent',
            name='carered_for_by',
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='carered_for_by',
            field=models.TextField(blank=True, verbose_name='Cared For By'),
        ),
    ]
