# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivingevents', '0005_auto_20170605_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='migrationevent',
            old_name='carered_for_by',
            new_name='cared_for_by',
        ),
    ]
