# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingevents', '0006_auto_20170605_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationevent',
            name='cared_for_by',
        ),
        migrations.AddField(
            model_name='migrationevent',
            name='cared_by',
            field=models.TextField(blank=True, verbose_name='Cared For By'),
        ),
    ]
