# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingevents', '0008_auto_20170605_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationevent',
            name='date_m_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='From (Month)'),
        ),
        migrations.AlterField(
            model_name='migrationevent',
            name='date_m_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='To (Month)'),
        ),
    ]
